### PR TITLE
updated resources (fomantic 2.8.8)

### PR DESCRIPTION
**Pull request by WalchAndreas**
updated fomantic (js / css / fonts)

### CODE REVIEW

**Comment by haraldsteinlechner** [comment]
cool, some thoughts:
1. this is just resources update, right? 
2. are there breaking changes which could break stuff? 
3. Also, what about updating jquery? we ship it, right? 
4. Is the license topic clean? should we make clear we are shipping this stuff?

**Comment by haraldsteinlechner** [comment]
that said, and when looking at the current situation. all those UI related things should actually be in aardvark.ui or aardvark.ui.primitives not service itself. are there reasons for the status quo?

**Comment by krauthaufen** [comment]
This would require everyone to add a special `assemblyWebPart` to their startup code. So this would break things everywhere and is pretty hard to remember when porting things three months from now.
That's why we left these things in Service afaik

As for semantic breaking changes we should consult their change-log?

**Comment by hyazinthh** [comment]
This branch contains more or less unrelated breaking changes, so we should use this as starting point for the next major version (5.4). There are some potential breaking changes on the horizon (e.g. golden layout, color picker), so it's probably not a good idea to release this fully yet.

Use the v54 branch (either directly or branch from it) for breaking changes that should make it into 5.4.

**Pull request closed without merging**
